# Generated by Django 4.2.6 on 2023-12-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_quatity_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='oder',
            new_name='order',
        ),
    ]
